services:
  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb-test-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test_notification_db --quiet
      interval: 10s
      retries: 5

  notification-service-test:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: notification-service-test
    volumes:
      - .:/workspace
      - ${HOME}/.m2:/root/.m2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-test:27017/test_notification_db
      - SPRING_DATA_MONGODB_DATABASE=test_notification_db
    working_dir: /workspace
    depends_on:
      mongodb-test:
        condition: service_healthy  # Ensures MongoDB is ready before starting tests
    command: |
      chmod +x /workspace/wait-for-it.sh && ./wait-for-it.sh mongodb-test:27017 -- mvn clean test

volumes:
  mongodb-test-data:
